version: '3.8'

services:
  db_loja:
    build:
      context: ./db_loja
    container_name: db_loja
    ports:
      - "3308:3306"
    
  db_dw:
    build:
      context: ./db_dw
    container_name: db_dw
    ports:
      - "3309:3306"